//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabreportPdf
    {
        public decimal Id { get; set; }
        public Nullable<decimal> pid { get; set; }
        public Nullable<decimal> Ipd { get; set; }
        public string Labref { get; set; }
        public Nullable<int> labid { get; set; }
        public Nullable<decimal> Billid { get; set; }
        public string vno { get; set; }
        public Nullable<System.DateTime> enterdon { get; set; }
        public string Url { get; set; }
        public string Location { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
        public string LabName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public string BillNo { get; set; }
        public string RefNo { get; set; }
        public int DoctorId { get; set; }
    
        public virtual Doctor Doctor { get; set; }
    }
}
