//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PateintLeadger
    {
        public int Id { get; set; }
        public decimal Billid { get; set; }
        public string godcode { get; set; }
        public Nullable<decimal> opdid { get; set; }
        public Nullable<decimal> counterid { get; set; }
        public decimal PId { get; set; }
        public Nullable<decimal> regtranid { get; set; }
        public Nullable<decimal> inpatientid { get; set; }
        public string vtype { get; set; }
        public string saletype { get; set; }
        public Nullable<System.DateTime> vdate { get; set; }
        public string vno { get; set; }
        public Nullable<decimal> accode { get; set; }
        public string remarks { get; set; }
        public string userid { get; set; }
        public Nullable<decimal> doctorid { get; set; }
        public string receiptno { get; set; }
        public Nullable<decimal> subtotal { get; set; }
        public Nullable<decimal> netamt { get; set; }
        public string timeoftran { get; set; }
        public string cancelled { get; set; }
        public Nullable<decimal> tailid { get; set; }
        public string salemode { get; set; }
        public string formno { get; set; }
        public string challanno { get; set; }
        public Nullable<System.DateTime> challandate { get; set; }
        public string billno { get; set; }
        public System.DateTime billdate { get; set; }
        public string orders { get; set; }
        public Nullable<decimal> currency { get; set; }
        public Nullable<decimal> convrate { get; set; }
        public Nullable<decimal> transcode { get; set; }
        public string modeofdespatch { get; set; }
        public string vehicleno { get; set; }
        public string grno { get; set; }
        public Nullable<System.DateTime> grdate { get; set; }
        public Nullable<decimal> gramount { get; set; }
        public string approved { get; set; }
        public string approvedby { get; set; }
        public string purtype { get; set; }
        public Nullable<decimal> tbillid { get; set; }
        public Nullable<decimal> cashcode { get; set; }
        public string contraloc { get; set; }
        public Nullable<decimal> purpricelist { get; set; }
        public string cancelleduserid { get; set; }
        public Nullable<System.DateTime> cancelledtime { get; set; }
        public string grnidlist { get; set; }
        public Nullable<decimal> autoposted { get; set; }
        public Nullable<decimal> schemeid { get; set; }
        public string pcode { get; set; }
        public string ipno { get; set; }
        public string entrytype { get; set; }
        public string Location { get; set; }
    }
}
