//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientLoginEntry
    {
        public int ID { get; set; }
        public Nullable<int> LoginAttempt { get; set; }
        public Nullable<bool> Locked { get; set; }
        public Nullable<System.DateTime> LoginAttemptDate { get; set; }
        public int PatientId { get; set; }
    
        public virtual PatientInfo PatientInfo { get; set; }
    }
}
